name: alsana_alharfiyin
description: A new Flutter project for craftsmen.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.2
  firebase_analytics: ^11.1.0
  firebase_crashlytics: ^4.0.2

  # State Management
  provider: ^6.1.2

  # UI & Utilities
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3 # <-- تمت الإضافة
  flutter_markdown: ^0.7.1   # <-- تمت الإضافة
  share_plus: ^9.0.0         # <-- تمت الإضافة

  # Audio
  audioplayers: ^6.0.0
  flutter_sound: ^9.3.0

  # App Updates
  upgrader: ^11.0.0

  # Ads
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/images/professions_icons/ # <-- تم التعطيل مؤقتاً لإصلاح خطأ التحذير
    # - assets/images/cities_icons/      # <-- تم التعطيل مؤقتاً لإصلاح خطأ التحذير
