name: alsana_alharfiyin
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # تم تحديثه ليتوافق مع المكتبات الحديثة

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (Updated)
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.2
  firebase_analytics: ^11.1.1
  firebase_crashlytics: ^4.0.2

  # State Management (Updated)
  provider: ^6.1.2

  # UI & Utilities (Updated)
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_markdown: ^0.7.1
  cached_network_image: ^3.3.1
  
  # Upgrader (The problematic package, now updated)
  upgrader: ^12.1.0

  # Device & OS Access (Updated)
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  record: ^5.0.5 # (هذا الإصدار لا يزال جيدًا)
  audioplayers: ^6.0.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  # Ads (Updated)
  google_mobile_ads: ^5.1.0

  # Image processing (Updated)
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # (Updated)

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/privacy_policy.md
    - assets/terms_of_service.md
