name: alsana_alharfiyin
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.19
  firebase_analytics: ^10.8.9
  firebase_crashlytics: ^3.4.18

  # State Management
  provider: ^6.0.5

  # UI & Utilities
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_markdown: ^0.6.20
  cached_network_image: ^3.3.1
  
  # المكتبة المحدثة
  upgrader: ^12.1.0

  # Device & OS Access
  image_picker: ^1.0.8
  permission_handler: ^11.3.1
  record: ^5.0.5
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  url_launcher: ^6.2.6
  share_plus: ^7.2.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Ads
  google_mobile_ads: ^4.0.0

  # Image processing
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/privacy_policy.md
    - assets/terms_of_service.md
